build:
	docker compose \
		-f minio/docker-compose.yaml up minio \
		build

up:
	docker compose \
		-f minio/docker-compose.yaml up minio -d

down:
	docker compose \
		-f minio/docker-compose.yaml down minio
