services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # MinIO S3 API
      - "9001:9001"     # MinIO web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/data:/data
    command: server /data --console-address ":9001"
    profiles: ["storage"]
