name: Linting & Testing

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
    - name: Lint with Pylint
      run: |
         pylint -j 2 models docker/airflow/dags unit_tests --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        python -m pytest
#    - name: Generate Confluence docs from catalog.yml
#      if: github.event_name == 'push'
#      env:
#        CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
#        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
#        CONFLUENCE_WORKSPACE_ADDRESS: ${{ secrets.CONFLUENCE_WORKSPACE_ADDRESS }}
#        CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
#        CONFLUENCE_PARENT_PAGE_ID: ${{ secrets.CONFLUENCE_PARENT_PAGE_ID }}
#      run: |
#        python database_schema/data_catalog_generation.py